name: structure_rv_data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  daily:
    runs-on: self-hosted

    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install all necessary packages
      run: pip install pandas paramiko numpy requests

    - name: Show working directory and contents
      run: |
        pwd
        ls -al

    - name: Show NumPy import path
      run: |
        python3 -c "import numpy; print('NumPy is being imported from:', numpy.__file__)"

    - name: Structure the data
      run: python 02b_strukturer_rv25_resultater.py

    - name: Update the DW files
      run: python 05b_opdater_rv_datafiler.py

    - name: Commit and push any changes
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
